name: insusty
description: A new Flutter project.


publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  carousel_slider: ^4.2.1
  nb_utils: ^4.6.25
  go_router: ^6.0.1
  url_strategy: ^0.2.0
  flutter_zoom_drawer: ^3.0.3
  get_it: ^7.2.0
  country_picker: ^2.0.19
  flutter_next: ^0.1.1
  animated_flip_counter: ^0.2.5
  firebase_core: ^2.4.1
  firebase_auth: ^4.2.5
  cloud_firestore: ^4.3.1
  video_player: ^2.5.1
  visibility_detector: ^0.3.3
  fl_chart: ^0.55.2
  flutter_stripe: ^8.0.0+1
  flutter_stripe_web: ^3.0.0
  stripe_checkout: ^1.0.0
  http: ^0.13.5
  dio: ^4.0.6
  js: ^0.6.5
  awesome_dialog: ^3.0.2
  shared_preferences: ^2.0.17
  code_editor: ^1.3.2
  flutter_html: ^3.0.0-alpha.6
  flutter_web_frame: ^0.0.3
  rive: ^0.11.2













flutter:


  uses-material-design: true


  assets:
    - images/
    - images/ui/
    - images/q&a/
    - images/ui/HomePage/
    - images/ui/LoginPage/
    - images/ui/Calculator/
    - images/ui/video/



  fonts:
    - family: nt
      fonts:
        - asset: fonts/NeutraText-Bold.otf
          weight: 700
        - asset: fonts/NeutraText-Book.otf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
