name: insusty
description: A new Flutter project.


publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  carousel_slider: ^4.2.1
  nb_utils: ^4.6.25
  go_router: ^6.0.0
  url_strategy: ^0.2.0
  flutter_zoom_drawer: ^3.0.3
  get_it: ^7.2.0
  country_picker: ^2.0.19
  flutter_next: ^0.1.1
  animated_flip_counter: ^0.2.5


dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:


  uses-material-design: true


  assets:
    - images/
    - images/ui/
    - images/ui/HomePage/
    - images/ui/LoginPage/
    - images/ui/Calculator/



  fonts:
    - family: nt
      fonts:
        - asset: fonts/NeutraText-Bold.otf
          weight: 700
        - asset: fonts/NeutraText-Book.otf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
