// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUa_S1oKdglM7L0Lk1v3Rf9CbHoC7H9OQ',
    appId: '1:1088009435867:web:2891534157356194b72afe',
    messagingSenderId: '1088009435867',
    projectId: 'insusty-app',
    authDomain: 'insusty-app.firebaseapp.com',
    storageBucket: 'insusty-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7ZIz3YBl6a2mW4V1zhuNGKAQxw5dcVWo',
    appId: '1:1088009435867:android:8b71bae1641398beb72afe',
    messagingSenderId: '1088009435867',
    projectId: 'insusty-app',
    storageBucket: 'insusty-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKtdeNELt4LMmX7xhpgKaCH9KSJa2sQ_g',
    appId: '1:1088009435867:ios:1299b12f2f41c912b72afe',
    messagingSenderId: '1088009435867',
    projectId: 'insusty-app',
    storageBucket: 'insusty-app.appspot.com',
    iosClientId: '1088009435867-0uimft492q2vv296thkhb66m1ffiso1h.apps.googleusercontent.com',
    iosBundleId: 'com.flutterfly.insusty.insusty',
  );
}
