List<String> questionEng = [
  "What is Insusty and how does it work?",
  "How do I create an Insusty account?",
  "How can I update my account information?",
  "Is my personal information secure with Insusty?",
  "Can I have multiple accounts?",
  "How do I delete my Insusty account?",
  "How do I earn Insusty points?",
  "What actions qualify for earning points?",
  "How do I check my points balance?",
  "What can I redeem my points for?",
  "Do Insusty points expire?",
  "Can I transfer my points to another user?",
  "I think my points balance is incorrect. What should I do?",
  "How are rewards delivered?",
  "How do I refer a friend to Insusty?",
  "Do I earn points for each successful referral?",
  "Can I refer businesses to join Insusty?",
  "What qualifies as a successful referral?",
  "How can I earn points by promoting sustainability at my workplace or school?",
  "What kind of proof do I need to submit?",
  "How many points can I earn by spreading awareness?",
  "What does it mean to offset my carbon footprint?",
  "How do I earn points for carbon offsetting?",
  "How is my carbon offsetting verified?",
  "I can't log in to my account. What should I do?",
  "How do I reset my password?",
  "The app/website is not working properly. What should I do?",
  "I have a suggestion or feature request.",
  "What brands are associated with Insusty?",
  "How do I suggest a brand to join Insusty?",
  "How do I report an issue with a partner brand?",
  "Can I earn points for purchases made with partner brands?",
  "How does Insusty protect my data?",
  "How can I report a security vulnerability?",
  "How can I opt-out of marketing communications?",
  "Are there any fees associated with using Insusty?",
  "How do I add or remove a payment method?",
  "What payment methods are accepted?",
  "Where can I find Insusty’s terms and conditions?",
  "Where can I find Insusty’s privacy policy?",
  "What is Insusty's policy on data protection and GDPR?",
  "What is Insusty and how does it benefit my brand?",
  "How do I register my brand with Insusty?",
  "Is there a fee to join the Insusty network?",
  "How do I update my brand profile?",
  "What kind of brands can join the Insusty network?",
  "How does the point system work for brands?",
  "How can I set up promotions to give out Insusty points?",
  "Can brands earn points?",
  "Can I customize the points offered for my products or services?",
  "How are points awarded to customers?",
  "Can my brand refer other brands to join Insusty?",
  "How do I collaborate with other brands on the Insusty platform?",
  "What kind of referral rewards are available to brands?",
  "How can Insusty help me increase customer engagement?",
  "What kind of analytics does Insusty offer for brands?",
  "How can I use data from Insusty to improve my sustainability efforts?",
  "How do I get technical support as a brand partner?",
  "I'm experiencing issues with the brand dashboard. What should I do?",
  "How do I report bugs or other issues with the platform?",
  "How does the payment system work for brands?",
  "How do I add or remove a payment method?",
  "What are the billing cycles?",
  "How do I set up promotions and special offers on Insusty?",
  "Can I feature my brand or products on Insusty's main page or app?",
  "What are the guidelines for marketing my brand on Insusty?",
  "Where can I find Insusty's terms of service for brands?",
  "What are the rules and guidelines for participating brands?",
  "What are my rights and responsibilities as a participating brand?",
  "How does Insusty handle data protection and GDPR compliance for brands?",
  "What sustainability criteria does my brand need to meet to join Insusty?",
  "How does Insusty verify the sustainability claims of a brand?",
  "Can I update or modify my brand's sustainability information?",
];

List<String> answersEng = [
  "Feel good while doing good! Make sustainable choices, earn points, and then shop with those points from some really cool, eco-friendly brands.",
  "Ready to join the movement? Head over to Insusty Sign Up and become part of our growing community!",
  "You're the boss of your account! Update your payment details, tweak your profile settings, and even take another swing at carbon calculations—all from your user dashboard.",
  "Rest easy! We use top-notch Flutter software and our servers are EU-based, adhering strictly to French laws. Your info is super secure with us.",
  "One awesome account per user, please! It's how we keep the playing field fair and square.",
  "We'd hate to see you go, but if you must, just shoot an email to contact@insusty.com and we'll guide you through it.",
  "The fun part! Earn points by subscribing to carbon offset projects. Your choices matter, and we want to reward you for them!",
  "Referrals, becoming an Insusty Ambassador—you name it! There's more than one way to be a sustainability superstar!",
  "Curious how you're doing? Peek at your dashboard for the latest on your points balance.",
  "Ready to cash in? Browse through our Brand Gallery, check out their sustainability impact, then go straight to their website and use your points for sweet discounts!",
  "No rush, no fuss. Use your points when you feel the time is right. No pressure here!",
  "We're working on it! For now, point transfers between users are on hold, but stay tuned for Insusty gift points!",
  "Something doesn't add up? Contact us at contact@insusty.com. We'll sort it out!",
  "Rewards are delivered in the form of points and are credited to your account as soon as you subscribe to a carbon offset project or successfully refer a friend who does the same.",
  "A referral link is generated for you in your user dashboard. Simply share that link with friends to refer them.",
  "Yes, you will earn 50 points for each successful referral.",
  "Absolutely, we welcome referrals for businesses that align with our sustainability values.",
  "A successful referral is confirmed when the friend you've referred subscribes to a carbon offset project through Insusty. You'll then receive points in your account.",
  "We're thrilled you're interested in spreading the word about sustainability! Join our Insusty Ambassador Program and earn a whopping 500 points. Just head over to your user dashboard and find the 'Ambassador Program' to get started. We couldn't be more excited to have you on board!",
  "Share pictures of your sustainability initiatives on social media and tag us. Then send the link to contact@insusty.com. If you're comfortable, we'd love to feature your incredible efforts on our own social platforms!",
  "You can earn 500 points per awareness session or coaching activity, and an additional 50 points for each successful referral you make. Your impact can really add up!",
  "Offsetting your carbon footprint means you're directly contributing to projects that reduce or remove greenhouse gas emissions from the atmosphere. It's a wonderful way to take immediate action against climate change.",
  "Simply subscribe to one of our carbon offset projects or purchase carbon offsets by the metric ton. Each metric ton offset gives you 100 points, equivalent to a 10% discount on your next purchase. It's a win-win for you and the planet!",
  "We work hand-in-hand with NGOs right from the conceptual stage, providing funds and support. You'll receive quarterly updates and dedicated certificates once credits are generated. Unlike other platforms, we go directly to where the impact is being created. Your trust and participation mean the world to us.",
  "Oh no! We're here to help. Just drop us an email at contact@insusty.com and we'll get you sorted out.",
  "No worries. Click on 'Forgot Password' while logging in and follow the steps. We understand these things happen.",
  "Oops! Please send us a screenshot of the issue to contact@insusty.com so we can fix it ASAP.",
  "We'd absolutely love to hear from you! Please share your ideas at contact@insusty.com.",
  "Discover the amazing brands we're partnered with by visiting our brand page.",
  "Know a brand that would be a great fit? Please introduce us at business@insusty.com.",
  "Should you encounter any issues, don't hesitate to reach out at contact@insusty.com.",
  "At Insusty, points are earned through your direct environmental actions, not purchases. We do this to emphasize genuine sustainable behavior over consumerism. The rewards you earn are discounts for future sustainable purchases!",
  "Fear not, your data is in safe hands with us! We've got the EU-compliant GDPR policy in place. Our database is as secure as a bank vault - we use MongoDB and the tried-and-true Flutter software. We're tighter than Fort Knox when it comes to sharing your data. Other sustainable brands on our network won't get a whiff of your info unless you're making a direct purchase from their site. The only time we spill the beans is when it comes to basic info, like the total number of points used by our members through our platform.",
  "Got a knack for spotting tech hiccups? Leave it to our tech wizards, Flutterfly Software. They're the Sherlock Holmes of security, and they'll handle any vulnerabilities that come our way. contact@insusty.com",
  "Had your fill of our updates? Just shoot us a message at contact@insusty.com, and we'll make sure your inbox is zen.",
  "We're all about giving back! Our platform is free to use. You can earn loyalty points by subscribing to a carbon offset project or other environmental initiatives, and then cash in those points for sweet discounts when shopping with our sustainable brand partners. It's a win-win for you and the planet!",
  "Easy peasy! Head to your profile settings, and you'll find the magic button under 'Payments.'",
  "We like to keep it simple and secure with Stripe. We accept VISA and other major cards, making your experience as smooth as silk.",
  "Right here! [Insert link] - Your guide to the ins and outs of our platform.",
  "Easy-peasy, it's right here [Insert link] - your privacy is our priority!",
  "All aboard the data protection train! Check out our GDPR and data protection policies [Insert link].",
  "Hold on to your eco-hats! Insusty is like a turbocharged sustainability party. Brands join our network to tap into the power of collective action. Customers can hop on board through API integration on your platform, earning points and scoring discounts. It's a win-win, boosting ROI and customer retention.",
  "Welcome to the Insusty family! Here's the scoop: First, we'll dive into your brand's unique sustainability needs. Have questions? Book a demo call, grill us, and let's make sure we're a perfect match. Next, our tech wizards will work their magic with a smooth API integration process. But wait, there's more! We'll set up your personal dashboard, your one-stop-shop for managing subscription payments. Once you've conquered the tech side, we'll get you onboarded, familiarize you with all the features, and prepare you for the journey ahead. Buckle up!",
  "Indeed, there's a subscription fee starting at €29, plus a 5-7% transaction commission for each sale that uses our points. All the juicy details are right here [Insert link].",
  "Brand dashboard, here we come! Fill out our brand form with your content and logos, and you're ready to roll.",
  "Calling all eco-warriors! Sustainable brands from any industry are welcome to join our green party.",
  "Our API connects seamlessly to your brand's platform. Insusty points are earned by users on our platform and can then be used on your website for purchases.",
  "Promotions, anyone? You can set them up based on your chosen plan, or spread the word through your newsletter.",
  "Nope, points are for our users to earn and redeem.",
  "Unfortunately, customization of the points offered for your products or services is not available at the moment. We have a standard points system in place, where 100 points equate to a 10% discount, and the maximum points that can be used per order is 200. This system helps maintain consistency and simplicity for our users. If you have any other questions or need further assistance, feel free to reach out!",
  "Customers are on a point-earning spree! They can earn points by subscribing to a carbon offset project, referring friends, becoming an ambassador, and spreading the Insusty love at their university or workplace. And soon, they'll be racking up points by participating in even more environmental and social initiatives.",
  "You're the best! Yes, you can refer other brands to join our eco-family. Just drop us a line at business@insusty.com.",
  "Ready to team up with fellow eco-champions? Shoot us an email at business@insusty.com, and we'll play matchmaker.",
  "Spread the love, earn discounts! Brands can offer discounts as referral rewards.",
  "We're your secret weapon for boosting customer engagement. Connect with eco-conscious consumers, align your brand with their values, and watch the engagement soar.",
  "Get ready for data galore! You'll have access to analytics on points used, products, brands users are interested in, transaction tracking, and soon, a feature to track your impact.",
  "Data is power! You can use the insights from Insusty to fine-tune your sustainability initiatives and make even greater positive impacts.",
  "Tech hiccup? No worries! Reach out to us at contact@insusty.com, and depending on your plan, you might even get priority support.",
  "Dashboard drama? Shoot us an email at contact@insusty.com, and we'll jump into action to save the day.",
  "Bugs beware! If you come across any issues, report them to us at contact@insusty.com, and we'll squash them pronto.",
  "Money matters! You can manage your payments right from your brand dashboard. Subscription fees are paid monthly through the dashboard.",
  "Change it up! Managing your payment methods is a breeze. You can do it right from your dashboard's payment settings.",
  "We offer flexibility! Billing cycles are available monthly or annually, so you can choose what works best for you.",
  "It's all about spreading the love with uniform offers. While we don't have special offers, you can update your content to keep things fresh.",
  "Absolutely! It's included in the plan. Showcase your brand and products to our eco-conscious community.",
  "We're all about transparency! We share an impact report of brands created by Insusty.",
  "Right here [Insert link] - Your go-to source for the nitty-gritty details.",
  "Honesty is the best policy! We expect participating brands to be truthful about their impact, pay on time, and avoid competing with other sustainable brands.",
  "As a participating brand, you have the right to access our eco-conscious community and reap the benefits. Your responsibilities include staying true to your sustainability efforts and abiding by the rules we've laid out.",
  "We've got your back on data protection and GDPR compliance. Check out our policies right here [Insert link].",
  "To join our eco-crew, your brand will need to pass our evaluation during onboarding.",
  "We're thorough! We conduct due diligence and provide consulting to ensure your sustainability claims align with reality.",
  "Absolutely! You can update your sustainability information quarterly and yearly and report it right on our platform. Keep those green efforts fresh!",
];

//////////////////////////////////////////

List<String> questionsFr = [
  "Qu'est-ce qu'Insusty et comment ça fonctionne ?",
  "Comment créer un compte Insusty ?",
  "Comment puis-je mettre à jour mes informations de compte ?",
  "Mes informations personnelles sont-elles sécurisées avec Insusty ?",
  "Puis-je avoir plusieurs comptes ?",
  "Comment supprimer mon compte Insusty ?",
  "Comment gagner des points Insusty ?",
  "Quelles actions sont éligibles pour gagner des points ?",
  "Comment vérifier le solde de mes points ?",
  "Que puis-je échanger contre mes points ?",
  "Les points Insusty expirent-ils ?",
  "Puis-je transférer mes points à un autre utilisateur ?",
  "Je pense que le solde de mes points est incorrect. Que dois-je faire ?",
  "Comment les récompenses sont-elles livrées ?",
  "Comment parrainer un ami à Insusty ?",
  "Gagne-t-on des points pour chaque parrainage réussi ?",
  "Puis-je recommander des entreprises pour rejoindre Insusty ?",
  "Qu'est-ce qui qualifie comme un parrainage réussi ?",
  "Comment gagner des points en promouvant la durabilité sur mon lieu de travail ou à mon école ?",
  "Quel genre de preuve dois-je soumettre ?",
  "Combien de points puis-je gagner en sensibilisant ?",
  "Que signifie compenser mon empreinte carbone ?",
  "Comment gagner des points pour la compensation carbone ?",
  "Comment ma compensation carbone est-elle vérifiée ?",
  "Je n'arrive pas à me connecter à mon compte. Que dois-je faire ?",
  "Comment réinitialiser mon mot de passe ?",
  "L'application/le site Web ne fonctionne pas correctement. Que dois-je faire ?",
  "J'ai une suggestion ou une demande de fonctionnalité. Comment puis-je la partager ?",
  "Quelles marques sont associées à Insusty ?",
  "Comment suggérer une marque pour rejoindre Insusty ?",
  "Comment signaler un problème avec une marque partenaire ?",
  "Puis-je gagner des points pour des achats effectués auprès de marques partenaires ?",
  "Comment Insusty protège-t-il mes données ?",
  "Comment signaler une vulnérabilité de sécurité ?",
  "Comment puis-je me désinscrire des communications marketing ?",
  "Y a-t-il des frais associés à l'utilisation d'Insusty ?",
  "Comment ajouter ou retirer un moyen de paiement ?",
  "Quels moyens de paiement sont acceptés ?",
  "Où puis-je trouver les conditions générales d'Insusty ?",
  "Où puis-je trouver la politique de confidentialité d'Insusty ?",
  "Quelle est la politique d'Insusty en matière de protection des données et de RGPD ?",
  "Qu'est-ce qu'Insusty et en quoi cela bénéficie-t-il à ma marque ?",
  "Comment enregistrer ma marque avec Insusty ?",
  "Y a-t-il des frais pour rejoindre le réseau Insusty ?",
  "Comment mettre à jour le profil de ma marque ?",
  "Quel type de marques peut rejoindre le réseau Insusty ?",
  "Comment fonctionne le système de points pour les marques ?",
  "Comment puis-je mettre en place des promotions pour distribuer des points Insusty ?",
  "Les marques peuvent-elles gagner des points ?",
  "Puis-je personnaliser les points offerts pour mes produits ou services ?",
  "Comment les points sont-ils attribués aux clients ?",
  "Ma marque peut-elle recommander d'autres marques pour rejoindre Insusty ?",
  "Comment collaborer avec d'autres marques sur la plateforme Insusty ?",
  "Quels types de récompenses de parrainage sont disponibles pour les marques ?",
  "Comment Insusty peut-il m'aider à augmenter l'engagement des clients ?",
  "Quel type d'analyses Insusty offre-t-il pour les marques ?",
  "Comment puis-je utiliser les données d'Insusty pour améliorer mes efforts en matière de durabilité ?",
  "Comment obtenir du support technique en tant que partenaire de la marque ?",
  "Je rencontre des problèmes avec le tableau de bord de la marque. Que dois-je faire ?",
  "Comment signaler des bugs ou d'autres problèmes avec la plateforme ?",
  "Comment fonctionne le système de paiement pour les marques ?",
  "Comment ajouter ou retirer un moyen de paiement ?",
  "Quels sont les cycles de facturation ?",
  "Comment mettre en place des promotions et des offres spéciales sur Insusty ?",
  "Puis-je mettre en avant ma marque ou mes produits sur la page principale d'Insusty ou sur l'application ?",
  "Quelles sont les lignes directrices pour la commercialisation de ma marque sur Insusty ?",
  "Où puis-je trouver les conditions de service d'Insusty pour les marques ?",
  "Quelles sont les règles et directives pour les marques participantes ?",
  "Quels sont mes droits et responsabilités en tant que marque participante ?",
  "Comment Insusty gère-t-il la protection des données et la conformité au RGPD pour les marques ?",
  "Quels critères de durabilité ma marque doit-elle respecter pour rejoindre Insusty ?",
  "Comment Insusty vérifie-t-il les affirmations de durabilité d'une marque ?",
  "Puis-je mettre à jour ou modifier les informations de durabilité de ma marque ?",
];

List<String> answersFr = [
  "Fais-toi plaisir tout en faisant le bien ! Adopte un mode de vie durable, cumule des points et utilise-les chez nos marques éco-responsables triées sur le volet.",
  "Prêt(e) à rejoindre le mouvement ? Clique sur Inscription Insusty et deviens membre de notre belle communauté !",
  "Ton compte, tes règles ! Tu peux mettre à jour tes infos, tes préférences de paiement, et même retenter des calculs carbone, tout ça depuis ton tableau de bord utilisateur.",
  "Pas de souci, tu es en sécurité ici ! Nous utilisons le logiciel Flutter pour une sécurité maximale et nos serveurs partenaires sont basés dans l'UE, en conformité avec les lois françaises.",
  "Un seul compte par utilisateur, s'il te plaît ! C'est notre façon de garder le jeu équitable pour tout le monde.",
  "Ça nous ferait vraiment de la peine, mais si tu dois partir, envoie-nous simplement un email à contact@insusty.com et nous te guiderons.",
  "La meilleure partie ! Gagne des points en t'abonnant à des projets de compensation carbone. Fais des choix qui comptent et sois récompensé(e) !",
  "Parrainages, Ambassadeur Insusty, et plus encore ! Il y a plein de façons de devenir un héros de la durabilité !",
  "Envie de savoir où tu en es ? Jette un coup d'œil à ton tableau de bord pour suivre en direct ton solde de points.",
  "Envie de faire des emplettes ? Visite notre Galerie de Marques, explore leur impact durable, puis file directement sur leur site pour utiliser tes points et obtenir de super réductions !",
  "Pas de pression, utilise tes points quand tu le sens ! Aucune urgence chez nous.",
  "C'est en cours ! Pour l'instant, le transfert de points entre utilisateurs n'est pas possible, mais restez à l'écoute pour des points-cadeaux Insusty !",
  "Un souci avec tes points ? Pas de problème, contacte-nous à contact@insusty.com. On règlera ça !",
  "Les points sont ajoutés à ton compte en un éclair dès que tu t'abonnes à un projet de compensation carbone ou que tu parraines avec succès un ami qui en fait de même.",
  "Partager, c'est aimer ! Génère un lien de parrainage depuis ton tableau de bord et invite tes amis à nous rejoindre dans cette belle aventure.",
  "Tu connais une entreprise durable qui devrait nous rejoindre ? On est tout ouïe !",
  "Dès que ton ami s'abonne à un projet de compensation carbone, des points frais et nouveaux s'ajoutent à ton compte ! J'espère que tout est clair ! Ensemble, rendons le monde meilleur, un point à la fois !",
  "Nous sommes ravis que vous souhaitiez parler de durabilité ! Rejoignez notre programme d'ambassadeur Insusty et gagnez 500 points incroyables. Rendez-vous simplement dans votre tableau de bord utilisateur et cherchez le 'Programme Ambassadeur' pour commencer. Nous sommes plus qu'heureux de vous avoir à bord !",
  "Partagez des photos de vos initiatives en matière de durabilité sur les réseaux sociaux et taguez-nous. Puis envoyez le lien à contact@insusty.com. Si vous êtes à l'aise, nous serions ravis de mettre en avant vos incroyables efforts sur nos propres plateformes sociales !",
  "Vous pouvez gagner 500 points par session de sensibilisation ou d'accompagnement, et 50 points supplémentaires pour chaque parrainage réussi. Votre impact peut vraiment s'accumuler !",
  "Compenser votre empreinte carbone signifie que vous contribuez directement à des projets visant à réduire ou à éliminer les émissions de gaz à effet de serre de l'atmosphère. C'est une merveilleuse façon de prendre une action immédiate contre le changement climatique.",
  "Il vous suffit de vous abonner à l'un de nos projets de compensation carbone ou d'acheter des crédits carbone par tonne métrique. Chaque tonne métrique compensée vous donne 100 points, équivalant à une réduction de 10 % sur votre prochain achat. C'est un gain mutuel pour vous et pour la planète !",
  "Nous travaillons main dans la main avec des ONG dès la phase conceptuelle, en fournissant des fonds et un soutien. Vous recevrez des mises à jour trimestrielles et des certificats dédiés une fois que les crédits auront été générés. Contrairement à d'autres plateformes, nous allons directement là où l'impact est créé. Votre confiance et votre participation signifient tout pour nous.",
  "Oh non ! Nous sommes là pour vous aider. Il vous suffit de nous envoyer un e-mail à contact@insusty.com et nous réglerons la situation pour vous.",
  "Pas de soucis. Cliquez sur 'Mot de passe oublié' lors de la connexion et suivez les étapes. Nous comprenons que ces choses arrivent.",
  "Oups ! Veuillez nous envoyer une capture d'écran du problème à contact@insusty.com afin que nous puissions le résoudre au plus vite.",
  "Nous serions absolument ravis de vous entendre ! Veuillez partager vos idées à contact@insusty.com.",
  '',
  "Découvrez les incroyables marques avec lesquelles nous sommes partenaires en visitant notre page dédiée aux marques.",
  "Connaissez-vous une marque qui serait parfaitement adaptée ? Merci de nous la présenter à business@insusty.com.",
  "Si vous rencontrez le moindre problème, n'hésitez pas à nous contacter à contact@insusty.com.",
  "Chez Insusty, les points sont gagnés grâce à vos actions environnementales directes, pas grâce à vos achats. Nous faisons cela pour mettre l'accent sur un comportement durable authentique plutôt que sur la consommation. Les récompenses que vous gagnez sont des réductions pour des achats futurs durables !",
  "Rassurez-vous, vos données sont entre de bonnes mains ! Nous disposons d'une politique conforme au RGPD de l'UE. Notre base de données est aussi sécurisée qu'un coffre-fort de banque - nous utilisons MongoDB et le logiciel éprouvé Flutter. Nous sommes plus stricts que Fort Knox en ce qui concerne le partage de vos données. Les autres marques durables de notre réseau n'auront pas accès à vos informations, sauf si vous effectuez un achat direct sur leur site. La seule fois où nous partageons des informations est pour des données de base, comme le nombre total de points utilisés par nos membres via notre plateforme.",
  "Vous avez un don pour repérer les problèmes techniques ? Laissez nos magiciens de la technologie, Flutterfly Software, s'en charger. Ils sont les Sherlock Holmes de la sécurité et gèrent toutes les vulnérabilités qui se présentent à nous. Contactez-nous à contact@insusty.com si vous repérez un problème.",
  "Vous en avez assez de nos mises à jour ? Il vous suffit de nous envoyer un message à contact@insusty.com, et nous veillerons à ce que votre boîte de réception retrouve sa sérénité.",
  "Nous sommes là pour donner ! Notre plateforme est gratuite. Vous pouvez gagner des points de fidélité en vous abonnant à un projet de compensation carbone ou à d'autres initiatives environnementales, puis échanger ces points contre des réductions lorsque vous faites vos achats chez nos partenaires de marques durables. C'est du gagnant-gagnant pour vous et la planète !",
  "Rien de plus simple ! Rendez-vous dans vos paramètres de profil, et vous trouverez le bouton magique sous 'Paiements'.",
  "Nous aimons la simplicité et la sécurité avec Stripe. Nous acceptons les cartes VISA et d'autres cartes majeures, ce qui rend votre expérience aussi fluide que de la soie.",
  "C'est par ici ! [Insérer le lien] - Votre guide pour tout savoir sur notre plateforme.",
  "Facile-peasy, c'est par ici [Insérer le lien] - votre vie privée est notre priorité !",
  "Tous à bord du train de la protection des données ! Découvrez nos politiques RGPD et de protection des données [Insérer le lien].",
  "Accrochez-vous à vos chapeaux verts ! Insusty est comme une fête de durabilité suralimentée. Les marques rejoignent notre réseau pour exploiter la puissance de l'action collective. Les clients peuvent monter à bord via l'intégration API sur votre plateforme, gagner des points et obtenir des réductions. C'est du gagnant-gagnant, avec un impact sur le retour sur investissement et la fidélisation des clients.",
  "Bienvenue dans la famille Insusty ! Voici comment ça se passe : Tout d'abord, nous plongerons dans les besoins uniques en durabilité de votre marque. Vous avez des questions ? Réservez un appel de démonstration, interrogez-nous, et vérifions que nous sommes le match parfait. Ensuite, nos magiciens de la technologie travailleront leur magie avec un processus d'intégration API en douceur. Mais attendez, il y a plus ! Nous mettrons en place votre tableau de bord personnel, votre guichet unique pour la gestion des paiements d'abonnement. Une fois que vous aurez maîtrisé la technique, nous vous intégrerons, vous familiariserons avec toutes les fonctionnalités et vous préparerons pour le voyage à venir. Attachez vos ceintures !",
  "En effet, il y a des frais d'abonnement à partir de 29 €, plus une commission de transaction de 5 à 7 % pour chaque vente utilisant nos points. Tous les détails croustillants sont ici [Insérer le lien].",
  "Direction le tableau de bord de la marque ! Remplissez notre formulaire de marque avec votre contenu et vos logos, et vous êtes prêt à partir.",
  "Appel à tous les éco-guerriers ! Les marques durables de toutes les industries sont les bienvenues pour rejoindre notre fête verte.",
  "Notre API se connecte parfaitement à la plateforme de votre marque. Les points Insusty sont gagnés par les utilisateurs sur notre plateforme et peuvent ensuite être utilisés sur votre site web pour des achats.",
  "Des promotions, ça vous dit ? Vous pouvez les mettre en place en fonction du plan que vous avez choisi, ou les diffuser via votre newsletter.",
  "Non, les points sont destinés à être gagnés et utilisés par nos utilisateurs.",
  "Malheureusement, la personnalisation des points offerts pour vos produits ou services n'est pas disponible pour le moment. Nous avons mis en place un système standard de points, où 100 points équivalent à une réduction de 10 %, et le nombre maximum de points pouvant être utilisés par commande est de 200. Ce système contribue à maintenir la cohérence et la simplicité pour nos utilisateurs. Si vous avez d'autres questions ou avez besoin d'une assistance supplémentaire, n'hésitez pas à nous contacter ! 😊🌿💚",
  "Les clients sont en mode collecte de points ! Ils peuvent gagner des points en s'abonnant à un projet de compensation carbone, en parrainant des amis, en devenant ambassadeurs et en faisant la promotion d'Insusty dans leur université ou lieu de travail. Et bientôt, ils accumuleront des points en participant à encore plus d'initiatives environnementales et sociales.",
  "Vous êtes le meilleur ! Oui, vous pouvez recommander d'autres marques pour rejoindre notre famille éco. Il vous suffit de nous envoyer un e-mail à business@insusty.com.",
  "Prêt à faire équipe avec d'autres champions de l'éco ? Envoyez-nous un e-mail à business@insusty.com, et nous jouerons les entremetteurs.",
  "Propagez l'amour, gagnez des réductions ! Les marques peuvent offrir des réductions en guise de récompense pour les recommandations.",
  "Nous sommes votre arme secrète pour augmenter l'engagement des clients. Connectez-vous avec les consommateurs soucieux de l'environnement, alignez votre marque sur leurs valeurs et observez l'engagement monter en flèche.",
  "Préparez-vous à une avalanche de données ! Vous aurez accès à des analyses sur les points utilisés, les produits, les marques qui intéressent les utilisateurs, le suivi des transactions et bientôt une fonction pour suivre votre impact.",
  "Les données, c'est le pouvoir ! Vous pouvez utiliser les informations d'Insusty pour affiner vos initiatives de durabilité et avoir un impact positif encore plus grand.",
  "Problème technique ? Pas de soucis ! Contactez-nous à contact@insusty.com, et en fonction de votre plan, vous pourriez même bénéficier d'un support prioritaire.",
  "Problème avec le tableau de bord de la marque ? Envoyez-nous un e-mail à contact@insusty.com, et nous interviendrons pour sauver la situation.",
  "Attention aux bugs ! Si vous rencontrez des problèmes, signalez-les-nous à contact@insusty.com, et nous les écraserons rapidement.",
  "Les finances, ça compte ! Vous pouvez gérer vos paiements directement depuis votre tableau de bord de marque. Les frais d'abonnement sont prélevés mensuellement via le tableau de bord.",
  "Changez les choses ! La gestion de vos méthodes de paiement est un jeu d'enfant. Vous pouvez le faire directement depuis les paramètres de paiement de votre tableau de bord.",
  "Nous offrons de la flexibilité ! Les cycles de facturation sont disponibles mensuellement ou annuellement, pour que vous puissiez choisir ce qui vous convient le mieux.",
  "Tout tourne autour de la diffusion de l'amour avec des offres uniformes. Bien que nous n'ayons pas d'offres spéciales, vous pouvez mettre à jour votre contenu pour le garder frais.",
  "Absolument ! C'est inclus dans le plan. Mettez en avant votre marque et vos produits auprès de notre communauté soucieuse de l'environnement.",
  "Nous sommes totalement transparents ! Nous partageons un rapport d'impact des marques créées par Insusty.",
  "C'est par ici [Insérer le lien] - Votre source incontournable pour tous les détails techniques.",
  "L'honnêteté est la meilleure politique ! Nous attendons des marques participantes qu'elles disent la vérité sur leur impact, paient en temps et en heure et évitent la concurrence avec d'autres marques durables.",
  "En tant que marque participante, vous avez le droit d'accéder à notre communauté éco-consciente et de récolter les avantages. Vos responsabilités consistent à rester fidèle à vos efforts en matière de durabilité et à respecter les règles que nous avons établies.",
  "Nous veillons à la protection des données et à la conformité au RGPD. Consultez nos politiques ici [Insérer le lien]",
  "Pour rejoindre notre équipe éco, votre marque devra réussir notre évaluation lors de l'intégration.",
  "Nous sommes méticuleux ! Nous réalisons des audits et fournissons des conseils pour nous assurer que vos revendications en matière de durabilité sont conformes à la réalité.",
  "Absolument ! Vous pouvez mettre à jour vos informations sur la durabilité trimestriellement et annuellement et les rapporter directement sur notre plateforme. Continuez à maintenir vos efforts verts !"
];

List apiQuestions = [
  'How It Work.',
  'Get Price API',
  'Save Purchase API',
];

List apiAnswer = [
  'There are two API to successfully embed Insusty Point System. First one ( getPrice ) will will give the discounted price when customer use their Insusty Points. Second one ( savePurchase ) will register the purchase on Insusty\'s System.',
  'Use this API to get discounted price of any product. Put 3 query parameter: customer email, No. of insusty points, and original cart value.',
  'Use this to register the purchase on Insusty\'s system. Put 4: query parameter: customer email, No. of insusty points, original cart value, and your insusty email'
];
